
server.port=8080
server.servlet.context-path=/digit-assignment
app.timezone=UTC

# Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/advocate_db?TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway Configuration
spring.flyway.url=jdbc:postgresql://localhost:5432/advocate_db?TimeZone=UTC
spring.flyway.user=postgres
spring.flyway.password=postgres
spring.flyway.table=flyway_schema_history
spring.flyway.baseline-on-migrate=true
spring.flyway.outOfOrder=true
spring.flyway.locations=classpath:/db/migration/main
spring.flyway.enabled=true

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=advocate-group
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Kafka Topics
advocate.kafka.create.topic=save-advocate
advocate.kafka.update.topic=update-advocate

# DIGIT Service URLs
egov.idgen.host=http://localhost:8285/
egov.idgen.path=egov-idgen/id/_generate

egov.mdms.host=http://localhost:8094/
egov.mdms.search.endpoint=egov-mdms-service/v2/_search

egov.workflow.host=http://localhost:8280/
egov.workflow.transition.path=egov-workflow-v2/egov-wf/process/_transition
egov.workflow.businessservice.search.path=egov-workflow-v2/egov-wf/businessservice/_search
egov.workflow.processinstance.search.path=egov-workflow-v2/egov-wf/process/_search

# DIGIT Persister
persister.save.advocate.topic=save-advocate
persister.update.advocate.topic=update-advocate
